from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
HTML=ROOT/'android-youtube-test/app/src/main/assets/geovision.html'
OUT=ROOT/'out/LAB_012_FAILOVER.html'
MANIFEST=ROOT/'android-youtube-test/app/src/main/AndroidManifest.xml'

def once(s, old, new):
    c=s.count(old)
    assert c==1, (old[:100], c)
    return s.replace(old,new,1)

def patch(path):
    s=path.read_text(encoding='utf-8')

    old='<div class="controls"><button id="menu" class="circle-btn">☰</button><button id="macro" class="circle-btn" title="Macroaree">◎</button><button id="locate" class="circle-btn" title="Posizione">●</button></div>'
    new='<div class="controls"><button id="menu" class="circle-btn" title="App e ricerche">☰</button><button id="mapsQuick" class="circle-btn" title="Mappe">⌖</button><button id="macro" class="circle-btn" title="Macroaree">◎</button><button id="locate" class="circle-btn" title="Posizione">●</button></div><div id="mapsQuickPanel" class="gv-map-quick-panel"><b>Mappe</b><button data-gv-map="leaflet">GeoVision</button><button data-gv-map="roadmap">Google</button><button data-gv-map="satellite">Satellite</button><button id="gvApiOpen" class="gv-api-open">Chiavi API</button></div>'
    s=once(s,old,new)

    css='''\n<style id="gv017-restore-style">\n.gv-map-quick-panel{position:absolute;z-index:1050;right:80px;top:128px;width:170px;background:#fff;border:1px solid #e4e8ee;border-radius:18px;padding:10px;display:none;box-shadow:none}.gv-map-quick-panel.show{display:grid;gap:7px}.gv-map-quick-panel b{font-size:13px;color:#64748b;padding:2px 4px}.gv-map-quick-panel button{border:1px solid #e4e8ee;background:#fff;color:#334155;border-radius:12px;padding:9px 10px;text-align:left;font-weight:700}.gv-map-quick-panel button.active{border-color:#8bb8ee;background:#eef6ff;color:#2563a8}.gv-map-quick-panel .gv-api-open{margin-top:2px;color:#2f7de1}\n#gvLocalApi{position:fixed;inset:0;z-index:5000;background:rgba(15,23,42,.25);display:flex;align-items:center;justify-content:center;padding:18px}#gvLocalApi .box{width:min(560px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:22px;padding:16px;border:1px solid #e4e8ee}#gvLocalApi header{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}#gvLocalApi h2{font-size:22px;margin:0;color:#172033}#gvLocalApi .x{border:0;background:#eef2f7;width:38px;height:38px;border-radius:50%;font-size:22px;color:#475569}#gvLocalApi .row{display:grid;grid-template-columns:1fr auto;gap:8px 10px;align-items:center;padding:10px 0;border-top:1px solid #eef2f7}#gvLocalApi .row:first-of-type{border-top:0}#gvLocalApi .name{font-weight:800;color:#26364a}#gvLocalApi .state{font-size:12px;color:#64748b}#gvLocalApi input[type=password]{grid-column:1/-1;width:100%;border:1px solid #dde3eb;border-radius:12px;padding:10px 12px;color:#334155;background:#fff}#gvLocalApi label{display:flex;align-items:center;gap:5px;font-size:12px;font-weight:800;color:#365f8d}#gvLocalApi input[type=checkbox]{width:18px;height:18px;accent-color:#2f7de1}#gvLocalApi .save{width:100%;margin-top:12px;border:0;border-radius:13px;background:#2f7de1;color:#fff;padding:11px 14px;font-weight:900}#gvLocalApi .note{font-size:12px;color:#64748b;margin:5px 0 10px}\n@media(max-width:600px){.gv-map-quick-panel{right:72px;top:118px}}\n</style>\n'''
    s=once(s,'</head>',css+'</head>')

    old_stop="""function stopSpeech() { speechToken++; speechQueue.length = 0; speechUtteranceSeq++; window.clearTimeout(speechWatchdog); speechPumpRunning = false; speaking = false; try {\n    window.speechSynthesis.cancel();\n}\ncatch { } $('#voice').classList.remove('active'); $('#nativeVoice').classList.remove('active'); }"""
    new_stop="""function stopSpeech() { speechToken++; speechQueue.length = 0; speechUtteranceSeq++; window.clearTimeout(speechWatchdog); speechPumpRunning = false; speaking = false; try {\n    window.GeoVisionTTS?.stop?.();\n}\ncatch { } try {\n    window.speechSynthesis.cancel();\n}\ncatch { } $('#voice').classList.remove('active'); $('#nativeVoice').classList.remove('active'); }\nwindow.gvNativeTtsState = state => { const on = state === 'start'; if (state === 'start' || state === 'done' || state === 'error') { speaking = on; $('#voice').classList.toggle('active', on); $('#nativeVoice').classList.toggle('active', on); } };"""
    s=once(s,old_stop,new_stop)

    old_speak="""function speak(text, append = false) { if (!('speechSynthesis' in window))\n    return; if (!append) {\n    stopSpeech();\n    try {\n        window.speechSynthesis.resume();\n    }\n    catch { }\n} const token = speechToken; for (const part of speechParts(text))\n    speechQueue.push({ text: part, token, retries: 0 }); pumpSpeech(); }"""
    new_speak="""function speak(text, append = false) { const parts = speechParts(text); if (!parts.length) return; try {\n    if (window.GeoVisionTTS && typeof window.GeoVisionTTS.speak === 'function') {\n        if (!append) stopSpeech();\n        speaking = true; $('#voice').classList.add('active'); $('#nativeVoice').classList.add('active');\n        parts.forEach((part, i) => window.GeoVisionTTS.speak(part, !!append || i > 0));\n        return;\n    }\n}\ncatch { } if (!('speechSynthesis' in window)) return; if (!append) {\n    stopSpeech();\n    try { window.speechSynthesis.resume(); } catch { }\n} const token = speechToken; for (const part of parts) speechQueue.push({ text: part, token, retries: 0 }); pumpSpeech(); }"""
    s=once(s,old_speak,new_speak)

    marker="function runGoogleDiagnostics(){GVMonitor.open();}"
    api_fn=r'''function gvLocalApiEnabled(){try{const x=JSON.parse(localStorage.getItem('geovision_api_enabled_v1')||'{}');return {google1:x.google1!==false,google2:x.google2!==false,google3:x.google3!==false,ai:x.ai!==false,youtube:x.youtube!==false};}catch{return {google1:true,google2:true,google3:true,ai:true,youtube:true};}}
function gvOpenLocalApiPanel(){
    document.getElementById('gvLocalApi')?.remove();
    const enabled=gvLocalApiEnabled(), names=['google1','google2','google3','ai','youtube'], labels=['Google 1','Google 2','Google 3','Intelligenza artificiale','YouTube'];
    const read=n=>{try{return localStorage.getItem(n)||'';}catch{return '';}};
    const vals={google1:read('geovision_google_maps_api_key_1')||read('geovision_google_maps_api_key'),google2:read('geovision_google_maps_api_key_2'),google3:read('geovision_google_maps_api_key_3'),ai:read('geovision_ai_api_key'),youtube:read('geovision_youtube_api_key')};
    const root=document.createElement('div');root.id='gvLocalApi';root.innerHTML='<section class="box"><header><h2>Chiavi API</h2><button class="x" aria-label="Chiudi">×</button></header><p class="note">Gestione locale semplice. Nessuna sincronizzazione automatica.</p><div class="rows"></div><button class="save">Salva e applica</button></section>';
    const rows=root.querySelector('.rows');names.forEach((n,i)=>{const r=document.createElement('div');r.className='row';r.dataset.name=n;r.innerHTML='<div><div class="name">'+labels[i]+'</div><div class="state">'+(vals[n]?'Configurata':'Chiave assente')+'</div></div><label><input type="checkbox" '+(enabled[n]?'checked':'')+'> ON</label><input type="password" autocomplete="off" spellcheck="false">';r.querySelector('input[type=password]').value=vals[n]||'';rows.appendChild(r);});
    document.body.appendChild(root);root.querySelector('.x').onclick=()=>root.remove();root.onclick=e=>{if(e.target===root)root.remove();};
    root.querySelector('.save').onclick=async()=>{const out={}, en={};names.forEach(n=>{const r=root.querySelector('[data-name="'+n+'"]');out[n]=r.querySelector('input[type=password]').value.trim();en[n]=r.querySelector('input[type=checkbox]').checked;});try{localStorage.setItem('geovision_google_maps_api_key_1',out.google1);localStorage.setItem('geovision_google_maps_api_key_2',out.google2);localStorage.setItem('geovision_google_maps_api_key_3',out.google3);localStorage.setItem('geovision_google_maps_api_keys',JSON.stringify([out.google1,out.google2,out.google3]));localStorage.setItem('geovision_google_enabled_v1',JSON.stringify([en.google1,en.google2,en.google3]));localStorage.setItem('geovision_api_enabled_v1',JSON.stringify(en));if(out.ai)localStorage.setItem('geovision_ai_api_key',out.ai);else localStorage.removeItem('geovision_ai_api_key');if(out.youtube)localStorage.setItem('geovision_youtube_api_key',out.youtube);else localStorage.removeItem('geovision_youtube_api_key');const maps=[out.google1,out.google2,out.google3], ons=[en.google1,en.google2,en.google3];let idx=maps.findIndex((v,i)=>v&&ons[i]);if(idx<0)idx=maps.findIndex(Boolean);if(idx<0)idx=0;googleKey=maps[idx]||'';localStorage.setItem('geovision_google_active_key_index',String(idx));if(googleKey)localStorage.setItem('geovision_google_maps_api_key',googleKey);else localStorage.removeItem('geovision_google_maps_api_key');setGoogleKeyState(googleKey?'checking':'error');root.remove();if(googleKey){try{await initGoogleMaps();toast('Chiavi salvate · Google Maps attiva');}catch(_){toast('Chiavi salvate · Google non disponibile');}}else{document.querySelector('.app')?.classList.remove('google-active');toast('Chiavi salvate');}}catch(_){toast('Salvataggio chiavi non riuscito');}};
}
function runGoogleDiagnostics(){gvOpenLocalApiPanel();}'''
    s=once(s,marker,api_fn)

    old_events="""$('#menu').onclick = () => $('#drawer').classList.toggle('show');\n$('#drawerClose').onclick = () => $('#drawer').classList.remove('show');\n$('#mapsSetup').onclick = () => GVMonitor.open();\n$('#mapsSave').onclick = () => GVMonitor.open();"""
    new_events="""$('#menu').onclick = () => { $('#mapsQuickPanel').classList.remove('show'); $('#drawer').classList.toggle('show'); };\n$('#drawerClose').onclick = () => $('#drawer').classList.remove('show');\n$('#mapsQuick').onclick = e => { e.preventDefault(); e.stopPropagation(); $('#drawer').classList.remove('show'); $('#mapsQuickPanel').classList.toggle('show'); };\n$('#gvApiOpen').onclick = () => { $('#mapsQuickPanel').classList.remove('show'); gvOpenLocalApiPanel(); };\ndocument.querySelectorAll('[data-gv-map]').forEach(btn => btn.onclick = async () => { const mode=btn.dataset.gvMap; if(mode==='leaflet'){ if(googleReady&&googleMap){try{const c=googleMap.getCenter();map.setView([c.lat(),c.lng()],googleMap.getZoom());}catch{}} document.querySelector('.app')?.classList.remove('google-active'); $('#mapsQuickPanel').classList.remove('show'); return; } if(!googleKey){gvOpenLocalApiPanel();return;} try{ if(!googleReady)await initGoogleMaps(); const c=map.getCenter(); googleMap?.setCenter({lat:c.lat,lng:c.lng}); googleMap?.setZoom(map.getZoom()); if(googleMap)googleMap.setMapTypeId(mode==='satellite'?'satellite':'roadmap'); document.querySelector('.app')?.classList.add('google-active'); $('#mapsQuickPanel').classList.remove('show'); }catch(_){toast('Google Maps non disponibile');} });\n$('#mapsSetup').onclick = () => gvOpenLocalApiPanel();\n$('#mapsSave').onclick = () => gvOpenLocalApiPanel();"""
    s=once(s,old_events,new_events)

    a=s.index("const sheet = $('#sheet'), sheetHead = $('#sheet .sheet-head');")
    b=s.index('updateReticleUi(false);',a)
    swipe="""const sheet = $('#sheet'), sheetHead = $('#sheet .sheet-head'), sheetBody = $('#sheetBody');\nconst sheetInteractive = el => !!(el?.closest?.('button,input,select,a,gmp-place-details'));\nsheet.addEventListener('pointerdown', e => { if (sheetInteractive(e.target)) return; if (!e.target.closest('.sheet-head') && sheetBody && sheetBody.scrollTop > 2) return; sheetDragStart = e.clientY; sheetDragging = true; sheet.style.transition = 'none'; try { sheet.setPointerCapture(e.pointerId); } catch { } });\nsheet.addEventListener('pointermove', e => { if (!sheetDragging) return; const dy = Math.max(0, e.clientY - sheetDragStart); if (dy > 0 && sheetBody && sheetBody.scrollTop > 2 && !e.target.closest('.sheet-head')) { sheetDragging=false; sheet.style.transform=''; return; } sheet.style.transform = `translate(-50%,${Math.min(dy,260)}px)`; });\nconst finishSheetDrag = e => { if (!sheetDragging) return; const dy = Math.max(0, e.clientY - sheetDragStart); sheetDragging = false; sheet.style.transition = ''; if (dy > 64) closeSheet(); else sheet.style.transform = ''; };\nsheet.addEventListener('pointerup', finishSheetDrag);\nsheet.addEventListener('pointercancel', finishSheetDrag);\n"""
    s=s[:a]+swipe+s[b:]

    path.write_text(s,encoding='utf-8')

patch(HTML)
if OUT.exists(): patch(OUT)
m=MANIFEST.read_text(encoding='utf-8')
if 'android.intent.action.TTS_SERVICE' not in m:
    if '</queries>' in m: m=m.replace('</queries>','<intent><action android:name="android.intent.action.TTS_SERVICE"/></intent></queries>',1)
    else: m=m.replace('<application','<queries><intent><action android:name="android.intent.action.TTS_SERVICE"/></intent></queries>\n    <application',1)
MANIFEST.write_text(m,encoding='utf-8')
print('LAB017 restored controls/API/TTS/swipe')
