plugins {
    id 'com.android.application'
}

android {
    namespace 'it.geovision.keybox'
    compileSdk 35

    signingConfigs {
        stableDebug {
            storeFile file('../../android-youtube-test/signing/geovision-debug-stable.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'it.geovision.keybox'
        minSdk 23
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode 2008
        versionName '8.0-monitor-switch'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
    }
}

dependencies {
    androidTestImplementation "androidx.test:runner:1.6.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
}
