plugins {
    id 'com.android.application'
}

android {
    namespace 'it.geovision.test'
    compileSdk 35

    defaultConfig {
        applicationId 'it.geovision.test'
        minSdk 23
        targetSdk 35
        versionCode 124
        versionName '1.24-stable-signing-base'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
