(function(){
'use strict';
const state=GVKeyState.create(localStorage),names=GVKeyState.NAMES,labels=['Google 1','Google 2','Google 3','Intelligenza artificiale','YouTube'];
const GOOGLE_RUNTIME='geovision_google_runtime_status_v2';let panel=null,busy=false,importTimer=0;const results={};
function status(t){const e=document.getElementById('gvMonitorStatus');if(e)e.textContent=t;}function runtime(){try{return JSON.parse(localStorage.getItem(GOOGLE_RUNTIME)||'{}')||{};}catch{return {};}}function googleRuntime(i){const r=runtime()[String(i)];return r&&typeof r==='object'?r:null;}
function refresh(){if(!panel)return;const keys=state.read(),a=state.active(),en=state.enabled();names.forEach((n,i)=>{const row=panel.querySelector('[data-name="'+n+'"]');if(!row)return;const off=i<3&&!en[i],missing=!keys[n];let r=null,text='',dot='unknown';if(i<3){r=googleRuntime(i);if(off){text='OFF manuale';}else if(missing){text='Chiave assente';dot='bad';}else if(r){dot=r.ok?'ok':'bad';text=(i===a.idx?'ATTIVA · ':'')+(r.text||'Stato Google');}else{text=i===a.idx?'ATTIVA · pronta':'ON · disponibile';dot=i===a.idx?'ok':'unknown';}}else{r=results[n];if(missing){text='Chiave assente';dot='bad';}else if(r){text=r.text;dot=r.ok?'ok':'bad';}else{text='Configurata';}}row.querySelector('.dot').dataset.state=dot;row.querySelector('.state').textContent=text;const sw=row.querySelector('.gv-key-toggle');if(sw)sw.checked=en[i];});}
function receive(k){clearTimeout(importTimer);try{state.apply(k);localStorage.removeItem('geovision_keys_pending_v1');status('Chiavi KeyBox applicate.');refresh();}catch(e){status(e.message);}const b=document.getElementById('gvImport');if(b)b.disabled=false;}window.gvReceiveKeyBox=receive;window.gvMonitorSync=receive;window.gvKeyBoxError=t=>{clearTimeout(importTimer);status(t||'KeyBox non disponibile');};
function close(){if(panel){panel.remove();panel=null;}}
function doImport(){if(!window.GeoVisionKeyBox?.importKeys)return;status('Carico le chiavi da KeyBox…');try{window.GeoVisionKeyBox.importKeys();}catch(_){status('KeyBox non disponibile');}}
function open(){close();panel=document.createElement('div');panel.id='gvMonitor';panel.innerHTML='<section class="monitor-card"><header><div><div class="eyebrow">GEOVISION · LAB 013</div><h2>Monitor API</h2></div><button class="close" aria-label="Chiudi">×</button></header><p class="note">Google 1/2/3: ON/OFF manuale e failover automatico.</p><div id="gvApiRows"></div><div class="actions"><button id="gvImport">Importa da KeyBox</button><button id="gvTest">Verifica AI / YouTube</button></div><button id="gvSave" class="primary wide">Salva in questa GeoVision</button><div id="gvMonitorStatus"></div></section>';const keys=state.read(),en=state.enabled();names.forEach((n,i)=>{const row=document.createElement('div');row.className='row';row.dataset.name=n;const toggle=i<3?'<label class="key-switch"><input class="gv-key-toggle" type="checkbox"><span>ON</span></label>':'';row.innerHTML='<div class="row-head"><span class="dot"></span><div class="row-title"><b>'+labels[i]+'</b><div class="state"></div></div>'+toggle+'</div><input type="password" id="gvKey'+i+'">';row.querySelector('input[type=password]').value=keys[n];if(i<3)row.querySelector('.gv-key-toggle').onchange=e=>{state.setEnabled(i,e.target.checked);window.GeoVisionKeyBox?.setGoogleEnabled?.(i,e.target.checked);refresh();};panel.querySelector('#gvApiRows').appendChild(row);});document.body.appendChild(panel);panel.querySelector('.close').onclick=close;panel.querySelector('#gvImport').onclick=doImport;panel.querySelector('#gvSave').onclick=()=>{const k={googleEnabled:state.enabled()};names.forEach((n,i)=>k[n]=panel.querySelector('#gvKey'+i).value);state.apply(k);refresh();};panel.querySelector('#gvTest').onclick=test;refresh();if(names.some(n=>!keys[n]))setTimeout(doImport,150);}
async function check(name,key){if(!key)return {ok:false,text:'Chiave assente'};try{let u,o={};if(name==='ai'){u='https://generativelanguage.googleapis.com/v1beta/models';o.headers={'x-goog-api-key':key};}else{u='https://www.googleapis.com/youtube/v3/videos?part=id&id=S0Q4_88y&key='+encodeURIComponent(key);}const r=await fetch(u,o);return {ok:r.ok,text:r.ok?'Accesso API verificato':'HTTP '+r.status};}catch{return {ok:false,text:'Non verificabile'};}}
async function test(){if(busy)return;busy=true;try{const k=state.read();results.ai=await check('ai',k.ai);results.youtube=await check('youtube',k.youtube);refresh();}finally{busy=false;}}
window.addEventListener('gv-google-runtime',refresh);window.GVMonitor={open,close,receive,refresh};window.GeoVisionKeyBox?.pageReady?.();
})();