package it.geovision.keybox;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.*;
import org.junit.runner.RunWith;
import android.content.*;
import android.os.Bundle;
import static org.junit.Assert.*;
@RunWith(AndroidJUnit4.class)
public class VaultTest {
 Context c;
 @Before public void setup(){c=InstrumentationRegistry.getInstrumentation().getTargetContext();c.getSharedPreferences("geovision_keybox_v1",0).edit().clear().commit();}
 @After public void clear(){c.getSharedPreferences("geovision_keybox_v1",0).edit().clear().commit();}
 @Test public void legacy005CiphertextStillReadable() throws Exception{KeyVault.put(c,"google1","SYNTHETIC_005");assertEquals("SYNTHETIC_005",KeyVault.readAll(c).getString("google1"));assertFalse(c.getSharedPreferences("geovision_keybox_v1",0).getString("google1","").contains("SYNTHETIC"));}
 @Test public void fiveKeysAtomicRoundtripAndEnabledDefaults() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"});Bundle b=KeyVault.readAll(c);assertEquals("g1",b.getString("google1"));assertEquals("g2",b.getString("google2"));assertEquals("g3",b.getString("google3"));assertEquals("ai",b.getString("ai"));assertEquals("yt",b.getString("youtube"));assertEquals(1,b.getLong("revision"));assertArrayEquals(new boolean[]{true,true,true},b.getBooleanArray("googleEnabled"));}
 @Test public void enabledFlagsPersistWithKeysAtomically() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"},new boolean[]{false,true,false});Bundle b=KeyVault.readAll(c);assertArrayEquals(new boolean[]{false,true,false},b.getBooleanArray("googleEnabled"));assertFalse(b.getBoolean("google1Enabled"));assertTrue(b.getBoolean("google2Enabled"));assertFalse(b.getBoolean("google3Enabled"));assertEquals("g2",b.getString("google2"));}
 @Test public void toggleOneGooglePreservesAllKeysAndIncrementsRevision() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"});long before=KeyVault.readAll(c).getLong("revision");KeyVault.setEnabled(c,1,false);Bundle b=KeyVault.readAll(c);assertArrayEquals(new boolean[]{true,false,true},b.getBooleanArray("googleEnabled"));assertEquals(before+1,b.getLong("revision"));assertEquals("g1",b.getString("google1"));assertEquals("g2",b.getString("google2"));assertEquals("g3",b.getString("google3"));assertEquals("ai",b.getString("ai"));assertEquals("yt",b.getString("youtube"));}
 @Test public void settingSameFlagAgainDoesNotBumpRevision() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"});KeyVault.setEnabled(c,0,true);assertEquals(1,KeyVault.readAll(c).getLong("revision"));}
 @Test public void invalidBatchLeavesPreviousVaultAndFlags() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"},new boolean[]{true,false,true});try{KeyVault.putAll(c,new String[]{"changed","invalid\nkey","g3","ai","yt"},new boolean[]{false,false,false});fail();}catch(IllegalArgumentException expected){}Bundle b=KeyVault.readAll(c);assertEquals("g1",b.getString("google1"));assertArrayEquals(new boolean[]{true,false,true},b.getBooleanArray("googleEnabled"));assertEquals(1,b.getLong("revision"));}
 @Test public void deletingOneSlotPreservesOthersAndFlags() throws Exception{KeyVault.putAll(c,new String[]{"g1","g2","g3","ai","yt"},new boolean[]{false,true,true});KeyVault.putAll(c,new String[]{"g1","","g3","ai","yt"},new boolean[]{false,true,true});Bundle b=KeyVault.readAll(c);assertEquals("",b.getString("google2"));assertEquals("g3",b.getString("google3"));assertArrayEquals(new boolean[]{false,true,true},b.getBooleanArray("googleEnabled"));assertEquals(2,b.getLong("revision"));}
 @Test public void corruptCiphertextRejectsWholeSnapshot() throws Exception{c.getSharedPreferences("geovision_keybox_v1",0).edit().putString("ai","AA==").commit();try{KeyVault.readAll(c);fail("Corruption must not export empty keys");}catch(Exception expected){}assertEquals("AA==",c.getSharedPreferences("geovision_keybox_v1",0).getString("ai",""));}
 @Test public void emptyAndWrongCountRejected() throws Exception{try{KeyVault.putAll(c,new String[]{"one"});fail();}catch(IllegalArgumentException expected){}assertEquals(0,KeyVault.readAll(c).getLong("revision"));}
 @Test public void signaturePermissionProtectsReceiver() throws Exception{android.content.pm.ActivityInfo i=c.getPackageManager().getReceiverInfo(new ComponentName(c,SyncReceiver.class),0);assertEquals("it.geovision.permission.KEYBOX_IMPORT",i.permission);assertTrue(i.exported);android.content.pm.PermissionInfo p=c.getPackageManager().getPermissionInfo(i.permission,0);assertEquals(android.content.pm.PermissionInfo.PROTECTION_SIGNATURE,p.protectionLevel);}
 @Test public void manifestReceiverDeclaresReadAndToggleActions() throws Exception{android.content.pm.PackageInfo p=c.getPackageManager().getPackageInfo(c.getPackageName(),android.content.pm.PackageManager.GET_RECEIVERS);assertNotNull(p.receivers);boolean found=false;for(android.content.pm.ActivityInfo i:p.receivers)if(i.name.endsWith("SyncReceiver"))found=true;assertTrue(found);}
 @Test public void rejectedRequestDoesNotSendOrMutateKeys(){int count=KeyVault.count(c);new SyncReceiver().onReceive(c,new Intent("unexpected"));new SyncReceiver().onReceive(c,new Intent("it.geovision.keybox.GET_KEYS_V1").putExtra("replyPackage","other.package").putExtra("nonce","test"));new SyncReceiver().onReceive(c,new Intent("it.geovision.keybox.SET_GOOGLE_ENABLED_V1").putExtra("sourcePackage","other.package").putExtra("index",0).putExtra("enabled",false));assertEquals(count,KeyVault.count(c));assertTrue(KeyVault.enabled(c)[0]);}
}
