const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('assert/strict'),path=require('path');
(async()=>{
 const root=path.resolve(__dirname,'../..');const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(root+'/out/'+(req.url.includes('baseline')?'madre2-baseline.html':'LAB_010_MONITOR_SYNC.html')));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});let apiRequests=0;const errors=[];
 await context.route('**/*',async route=>{const u=route.request().url();if(u.startsWith(origin))return route.continue();if(u.includes('leaflet.js'))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(require.resolve('leaflet/dist/leaflet.js'),'utf8')});if(u.includes('leaflet.css'))return route.fulfill({contentType:'text/css',body:fs.readFileSync(require.resolve('leaflet/dist/leaflet.css'),'utf8')});if(u.includes('html2canvas'))return route.fulfill({contentType:'application/javascript',body:''});if(u.includes('places.googleapis.com')||u.includes('generativelanguage.googleapis.com')||u.includes('youtube/v3')){apiRequests++;return route.fulfill({status:u.includes('youtube/v3')?403:200,contentType:'application/json',body:'{"places":[],"models":[]}'});}return route.abort();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.locator('#keyStatus').waitFor();await page.locator('#keyStatus').click();assert.equal(await page.locator('#gvMonitor').count(),1);assert.equal(await page.locator('#gvMonitor input[type=password]').count(),5);assert.equal(apiRequests,0,'opening must not call APIs');
 await page.getByRole('button',{name:'Importa da KeyBox',exact:true}).click();assert.match(await page.locator('#gvMonitorStatus').innerText(),/Android/);
 const fixture={google1:'TEST_GOOGLE_1',google2:'TEST_GOOGLE_2',google3:'TEST_GOOGLE_3',ai:'TEST_AI',youtube:'TEST_YT',revision:1};await page.evaluate(k=>GVKeyState.create(localStorage).apply(k),fixture);
 await page.getByRole('button',{name:'Chiudi',exact:true}).click();await page.locator('#keyStatus').click();assert.equal(await page.locator('#gvKey0').inputValue(),fixture.google1);assert(!await page.locator('#gvMonitor').innerText().then(t=>t.includes(fixture.google1)));
 await page.getByRole('button',{name:'Verifica API',exact:true}).click();await page.waitForFunction(()=>document.getElementById('gvMonitorStatus').textContent.startsWith('Verifica terminata'));assert.equal(apiRequests,5);assert.equal(await page.locator('.dot[data-state="ok"]').count(),4);assert.equal(await page.locator('.dot[data-state="bad"]').count(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('geovision_google_active_key_index')),'0');
 await page.getByRole('button',{name:'Diagnostica schede e foto Google'}).click();await page.waitForFunction(()=>!document.getElementById('gvGoogleDetails').disabled);assert((await page.locator('#googleDiagRows').innerText()).includes('Maps JavaScript'));
 await page.evaluate(k=>gvMonitorSync({...k,google1:'UPDATED',revision:2}),fixture);assert.equal(await page.evaluate(()=>localStorage.getItem('geovision_google_maps_api_key')),fixture.google1);await page.locator('#gvApplyPending').waitFor({state:'visible'});await page.screenshot({path:root+'/out/Monitor_API_LAB_010.png',fullPage:true});
 for(let i=0;i<3;i++){await page.getByRole('button',{name:'Chiudi',exact:true}).click();await page.locator('#keyStatus').click();assert.equal(await page.locator('#gvMonitor').count(),1);}
 assert.equal(await page.evaluate(()=>document.getElementById('gvMonitor').querySelector('.monitor-card').scrollWidth<=document.getElementById('gvMonitor').querySelector('.monitor-card').clientWidth),true,'no horizontal overflow');
 await page.getByRole('button',{name:'Applica chiavi ricevute e riavvia'}).click();await page.waitForTimeout(700);assert.equal(await page.evaluate(()=>localStorage.getItem('geovision_keys_pending_v1')),null);assert.equal(await page.evaluate(()=>GVKeyState.create(localStorage).read().google1),'UPDATED');
 // Original controls and Google card markup are identical after added panel is closed.
 const appMarkup=await page.locator('#app').innerHTML();const baseline=await context.newPage();await baseline.goto(origin+'/baseline');await baseline.locator('#keyStatus').waitFor();assert.equal(await baseline.locator('#sheet').innerHTML(),await page.locator('#sheet').innerHTML());assert.equal(await baseline.locator('#drawer').locator('.grid').innerHTML(),await page.locator('#drawer').locator('.grid').innerHTML());assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS browser: real toolbar opens Monitor; five masked slots; zero automatic API probes; 5 explicit probes; truthful mixed statuses; no key rotation; original diagnostics callable; late sync staged; single modal across reopen; mobile overflow; apply/reload once; original card/social markup preserved; zero page errors.');
 await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
